"""jobs — очередь заданий и их события

Две таблицы и ни одной правки чужих: `jobs` и `job_events`.
Сверено с собственным списком — `create_table` ровно два, `alter` ни одного;
всё, что тут есть, объявлено в `api/jobs/models.py` и нигде больше.

Внешние ключи оба с `ON DELETE CASCADE`, и оба не для порядка:

* `jobs.user_id → users.id` — удалённый аккаунт уносит с собой
  всё своё. Без каскада в очереди остались бы строки с `payload`, то есть с
  работой человека, которого больше нет;
* `jobs.project_id → projects.id` — проект, убранный из корзины физически,
  уносит задания, которые в нём работали: задание на каталог, которого нет,
  воркер всё равно взять не сможет, а в списке оно будет висеть вечно;
* `job_events.job_id → jobs.id` — события живут ровно столько же, сколько
  задание. Уборка (`jobs.service.убрать_старые`) сносит их и явным запросом
  тоже: каскад делает то же самое, но по строке за раз, а событий на задание
  бывают тысячи.

Индексов три, и каждый под ровно один запрос: `(status, created_at)` — то, что
спрашивает воркер («самое старое из ждущих»), `(user_id, status)` — то, что
спрашивает человек, `(project_id)` — то, что спрашивает страница проекта.
Уникальный `(job_id, seq)` у событий — не украшение, а заслон: два писателя
одного задания столкнутся на нём, а не разъедутся молча, оставив в потоке дыру.

Индексы созданы через `batch_alter_table` — так их выписал `--autogenerate` на
SQLite, и переписывать это на `op.create_index` незачем: batch на только что
созданной таблице не пересоздаёт её, а просто добавляет индексы.

revision: 3cb2572ff488
down_revision: c3a71f0d94e6
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '3cb2572ff488'
down_revision = 'c3a71f0d94e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('progress', sa.JSON(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('spent_units', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_jobs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_project', ['project_id'], unique=False)
        batch_op.create_index('ix_jobs_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_jobs_user_status', ['user_id', 'status'], unique=False)

    op.create_table('job_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_events_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_events'))
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index('ix_job_events_job_seq', ['job_id', 'seq'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index('ix_job_events_job_seq')

    op.drop_table('job_events')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_user_status')
        batch_op.drop_index('ix_jobs_status_created')
        batch_op.drop_index('ix_jobs_project')

    op.drop_table('jobs')
    # ### end Alembic commands ###
