"""tokens admin — внешние ключи, события безопасности, флаг админа и лимиты

Две таблицы и две колонки. Сверено со своим списком:
`create_table` ровно два (`api_tokens`, `security_events`), `add_column` ровно
два (`users.is_admin`, `users.limits`), чужого не тронуто ничего.

Почему колонки в чужой таблице всё-таки здесь. `is_admin` и `limits`
принадлежат `users`, чужой таблице, но заводить ради булева поля вторую
таблицу (`admins`) значило бы join на каждый запрос админки и второе место, где
живёт ответ «кто владелец»; а `limits` — мешок личных лимитов, которые ставит
владелец в админке, и жить он обязан там же, где план. Правило «одна миграция
на подпакет» при этом не нарушено: правка чужой таблицы — часть этой миграции,
а не отдельная.

`server_default` у обеих — не украшение, а единственный способ добавить
`NOT NULL`-колонку в непустую таблицу: без умолчания у всех, кто уже
зарегистрирован, в ней оказался бы NULL, и batch-пересборка SQLite упала бы
прямо на выкате. Умолчания остаются в схеме навсегда, и это правильно:
администратор — исключение, а не состояние по умолчанию, а пустой мешок
лимитов означает «как у всех».

Внешние ключи разные намеренно, и разница осмысленная:

* `api_tokens.user_id → users.id` с `ON DELETE CASCADE`: удалили аккаунт —
  ключей его нет. Ключ, переживший владельца, открывал бы доступ никому;
* `security_events.user_id → users.id` с `ON DELETE SET NULL`: «для журнала
  безопасности оставить только обезличенную запись». Каскад унёс бы след «с
  этого адреса ломились», то есть ровно то, ради чего журнал и ведётся.

Индексы — под запросы, а не для полноты: `api_tokens.token_hash` уникальный
(по нему ищется предъявленный ключ, и он же заслон от двух строк с одним
хешем), `prefix` и `user_id` — под список ключей человека, у событий
`(kind, created_at)` — под единственный запрос админки «последние события,
можно с отбором по виду».

revision: 7f7799c6dac1
down_revision: 3cb2572ff488
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '7f7799c6dac1'
down_revision = '3cb2572ff488'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=8), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_tokens'))
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_tokens_prefix'), ['prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('security_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_security_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_events'))
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_events_kind'), ['kind'], unique=False)
        batch_op.create_index('ix_security_events_kind_created', ['kind', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        # `server_default` дописан руками — см. докстроку: без него колонка не
        # добавится в таблицу, где уже есть люди.
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))
        batch_op.add_column(sa.Column('limits', sa.JSON(), nullable=False,
                                      server_default=sa.text("'{}'")))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('limits')
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_events_user_id'))
        batch_op.drop_index('ix_security_events_kind_created')
        batch_op.drop_index(batch_op.f('ix_security_events_kind'))

    op.drop_table('security_events')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_api_tokens_prefix'))

    op.drop_table('api_tokens')
    # ### end Alembic commands ###
