"""notifications — колокольчик (агент B, ночь 2).

Одна таблица: `notifications`. Решение владельца §11 — **писем о готовности
нет**, значит единственный способ узнать, что работа кончилась, — увидеть это в
интерфейсе, а поток событий закрытую вкладку не переживает.

`down_revision` — `7f7799c6dac1` (внешние токены и админка агента C), голова на
момент создания. Правкой чужой цепочки это не является: миграция создана после
неё, на чистом томе, поднятом до head, и `alembic heads` показывал ровно одну
голову. Голова после этой ревизии — она сама.

Два внешних ключа и оба `CASCADE`, и это не украшение:

* `user_id` — обещание §7 «удалили аккаунт — нет и его данных»;
* `job_id` — срок хранения заданий (90 дней) уносит и уведомления о них, иначе
  колокольчик ссылался бы на карточку, которой уже нет.

`UNIQUE (job_id)` — то, чем держится «уведомление о задании ровно одно».
Проверкой в коде это не держится: два воркера, закрывшие одно задание, разошлись
бы двумя строками, и человек увидел бы «готово» дважды.

Revision ID: eef3027c39f2
Revises: 7f7799c6dac1
Create Date: 2026-09-04 11:26:27.272886
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'eef3027c39f2'
down_revision = '7f7799c6dac1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_notifications_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('job_id', name=op.f('uq_notifications_job_id'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'read_at', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')

    op.drop_table('notifications')
    # ### end Alembic commands ###
